[package]
name = "vs-frameblender-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rustsynth = {version = "=0.6.0", features=["proc-macro"]}

[features]
default = ["simd"]
simd = []

[lib]
name = "frameblender_rs"
crate-type = ["cdylib"]