[package]
name = "vs-frameblender-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rustsynth = {version = "=0.5.1", features = ["vapoursynth-functions"] }
rustsynth-derive = "=0.5.1"

[features]
default = ["simd"]
simd = []

[lib]
name = "frameblender_rs"
crate-type = ["cdylib"]